---
- hosts: all
  become: yes
  tasks:
    - name: Build a docker image
      command: docker build -t web /home/ec2-user
          
    - name: Run a container
      command: docker container run -d -p 80:80 --name mynewapp web
